web:
  restart: always
  build: .
  command: npm start
  links:
   - db
  ports:
   - 3000:3000
  environment:
   - PORT=3000
   - MONGO=mongodb://db:27017/testing
  volumes:
   - .:/usr/src/web/
db:
  restart: always
  image: mongo:3.2
  ports:
   - 27017:27017